package example;


/**
* example/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/reposComputoDistribuido/corba/corba/CorbaFiboInterface/src/fibonacci.idl
* lunes 19 de julio de 2021 05:24:27 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
